/* AUTOGENERATED by hw/audio/build_audio_mif.py. DO NOT EDIT. */
parameter logic [14:0] SFX_START [1:8] = '{15'd0, 15'd2400, 15'd4800, 15'd7200, 15'd9600, 15'd12000, 15'd14400, 15'd16800};
parameter logic [14:0] SFX_END   [1:8] = '{15'd2399, 15'd4799, 15'd7199, 15'd9599, 15'd11999, 15'd14399, 15'd16799, 15'd19199};
