# TCL File Generated by Component Editor 21.1
# Thu May 09 22:58:20 EDT 2024
# DO NOT MODIFY


# 
# fpga_audio "fpga_audio" v1.0
#  2024.05.09.22:58:20
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module fpga_audio
# 
set_module_property DESCRIPTION ""
set_module_property NAME fpga_audio
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME fpga_audio
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL fpga_audio
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file fpga_audio.sv SYSTEM_VERILOG PATH fpga_audio.sv TOP_LEVEL_FILE
add_fileset_file combined_audio.mif MIF PATH combined_audio.mif
add_fileset_file audio_rom.v VERILOG PATH audio_rom.v


# 
# parameters
# 


# 
# module assignments
# 
set_module_assignment embeddedsw.dts.group audio
set_module_assignment embeddedsw.dts.name fpga_audio
set_module_assignment embeddedsw.dts.vendor csee4840


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point audio_out_l
# 
add_interface audio_out_l avalon_streaming start
set_interface_property audio_out_l associatedClock clock
set_interface_property audio_out_l associatedReset reset
set_interface_property audio_out_l dataBitsPerSymbol 8
set_interface_property audio_out_l errorDescriptor ""
set_interface_property audio_out_l firstSymbolInHighOrderBits true
set_interface_property audio_out_l maxChannel 0
set_interface_property audio_out_l readyLatency 0
set_interface_property audio_out_l ENABLED true
set_interface_property audio_out_l EXPORT_OF ""
set_interface_property audio_out_l PORT_NAME_MAP ""
set_interface_property audio_out_l CMSIS_SVD_VARIABLES ""
set_interface_property audio_out_l SVD_ADDRESS_GROUP ""

add_interface_port audio_out_l left_chan_ready ready Input 1
add_interface_port audio_out_l sample_data_l data Output 16
add_interface_port audio_out_l sample_valid_l valid Output 1


# 
# connection point audio_out_r
# 
add_interface audio_out_r avalon_streaming start
set_interface_property audio_out_r associatedClock clock
set_interface_property audio_out_r associatedReset reset
set_interface_property audio_out_r dataBitsPerSymbol 8
set_interface_property audio_out_r errorDescriptor ""
set_interface_property audio_out_r firstSymbolInHighOrderBits true
set_interface_property audio_out_r maxChannel 0
set_interface_property audio_out_r readyLatency 0
set_interface_property audio_out_r ENABLED true
set_interface_property audio_out_r EXPORT_OF ""
set_interface_property audio_out_r PORT_NAME_MAP ""
set_interface_property audio_out_r CMSIS_SVD_VARIABLES ""
set_interface_property audio_out_r SVD_ADDRESS_GROUP ""

add_interface_port audio_out_r sample_valid_r valid Output 1
add_interface_port audio_out_r sample_data_r data Output 16
add_interface_port audio_out_r right_chan_ready ready Input 1


# 
# connection point avalon_slave
# 
add_interface avalon_slave avalon end
set_interface_property avalon_slave addressUnits WORDS
set_interface_property avalon_slave associatedClock clock
set_interface_property avalon_slave associatedReset reset
set_interface_property avalon_slave bitsPerSymbol 8
set_interface_property avalon_slave burstOnBurstBoundariesOnly false
set_interface_property avalon_slave burstcountUnits WORDS
set_interface_property avalon_slave explicitAddressSpan 0
set_interface_property avalon_slave holdTime 0
set_interface_property avalon_slave linewrapBursts false
set_interface_property avalon_slave maximumPendingReadTransactions 0
set_interface_property avalon_slave maximumPendingWriteTransactions 0
set_interface_property avalon_slave readLatency 0
set_interface_property avalon_slave readWaitTime 1
set_interface_property avalon_slave setupTime 0
set_interface_property avalon_slave timingUnits Cycles
set_interface_property avalon_slave writeWaitTime 0
set_interface_property avalon_slave ENABLED true
set_interface_property avalon_slave EXPORT_OF ""
set_interface_property avalon_slave PORT_NAME_MAP ""
set_interface_property avalon_slave CMSIS_SVD_VARIABLES ""
set_interface_property avalon_slave SVD_ADDRESS_GROUP ""

add_interface_port avalon_slave address address Input 4
add_interface_port avalon_slave chipselect chipselect Input 1
add_interface_port avalon_slave write write Input 1
add_interface_port avalon_slave writedata writedata Input 8
set_interface_assignment avalon_slave embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave embeddedsw.configuration.isPrintableDevice 0

