#!/usr/bin/env python3
"""
build_audio_mif.py — turn manifest.json + WAV assets into:
  - hw/bgm_rom.mem
  - hw/sfx_rom.mem
  - hw/sfx_offsets.svh

Stdlib-only (wave, struct, json, pathlib).

Contributors pre-process their source audio to 8 kHz 16-bit mono WAV before
putting files in assets/. This script refuses any WAV that doesn't match.

Missing SFX WAVs are filled with silence (manifest.silent_samples_per_missing_cue
zero samples) so the output files are always a consistent size — this is what
makes Scope A (no SFX assets yet) a purely asset-less build.
"""
import json
import struct
import sys
import wave
from pathlib import Path


SCRIPT_DIR = Path(__file__).resolve().parent    # hw/audio
HW_DIR     = SCRIPT_DIR.parent                  # hw/

EXPECTED_RATE    = 8000
EXPECTED_WIDTH   = 2           # 16-bit
EXPECTED_CHANNELS = 1


def read_pcm16_mono(path: Path) -> list[int]:
    """Read a WAV file; return a list of signed int16 samples. Validates format."""
    with wave.open(str(path), "rb") as w:
        if w.getframerate() != EXPECTED_RATE:
            sys.exit(f"ERROR: {path}: sample rate {w.getframerate()} != {EXPECTED_RATE}")
        if w.getsampwidth() != EXPECTED_WIDTH:
            sys.exit(f"ERROR: {path}: sample width {w.getsampwidth()} != {EXPECTED_WIDTH}")
        if w.getnchannels() != EXPECTED_CHANNELS:
            sys.exit(f"ERROR: {path}: channels {w.getnchannels()} != {EXPECTED_CHANNELS}")
        raw = w.readframes(w.getnframes())
    n = len(raw) // EXPECTED_WIDTH
    return list(struct.unpack(f"<{n}h", raw))


def write_mem(path: Path, samples: list[int]) -> None:
    """Write one 16-bit hex per line, two's-complement."""
    with open(path, "w") as f:
        for s in samples:
            if s < 0:
                s = s + (1 << 16)
            f.write(f"{s:04x}\n")


def main() -> None:
    manifest_path = SCRIPT_DIR / "manifest.json"
    manifest = json.loads(manifest_path.read_text())

    silent_len = manifest.get("silent_samples_per_missing_cue", 2400)

    # --- BGM ---
    bgm_file = SCRIPT_DIR / manifest["bgm"]["file"]
    if bgm_file.exists():
        bgm_samples = read_pcm16_mono(bgm_file)
        print(f"BGM: {bgm_file.name} = {len(bgm_samples)} samples "
              f"({len(bgm_samples)/EXPECTED_RATE:.2f} s)")
    else:
        bgm_samples = [0] * silent_len
        print(f"BGM: {bgm_file.name} MISSING, using {silent_len} silent samples")
    write_mem(HW_DIR / "bgm_rom.mem", bgm_samples)

    # --- SFX ---
    sfx_samples: list[int] = []
    sfx_start: list[int] = [0] * 9    # 1-indexed, index 0 unused
    sfx_end:   list[int] = [0] * 9

    # Sort cues by cue_id to pack deterministically
    cues = sorted(manifest["sfx"], key=lambda c: c["cue_id"])
    for cue in cues:
        cid = cue["cue_id"]
        if not (1 <= cid <= 8):
            sys.exit(f"ERROR: manifest cue_id {cid} out of range 1..8")
        f = SCRIPT_DIR / cue["file"]
        if f.exists():
            samples = read_pcm16_mono(f)
        else:
            samples = [0] * silent_len
            print(f"SFX cue {cid} ({cue['name']}): MISSING, using {silent_len} silent samples")

        start = len(sfx_samples)
        end   = start + len(samples) - 1
        sfx_start[cid] = start
        sfx_end[cid]   = end
        sfx_samples.extend(samples)

    write_mem(HW_DIR / "sfx_rom.mem", sfx_samples if sfx_samples else [0])
    print(f"SFX total: {len(sfx_samples)} samples ({len(sfx_samples)/EXPECTED_RATE:.2f} s)")

    # --- Offsets include ---
    with open(HW_DIR / "sfx_offsets.svh", "w") as f:
        f.write("/* AUTOGENERATED by hw/audio/build_audio_mif.py. DO NOT EDIT. */\n")
        f.write("parameter logic [14:0] SFX_START [1:8] = '{")
        f.write(", ".join(f"15'd{sfx_start[i]}" for i in range(1, 9)))
        f.write("};\n")
        f.write("parameter logic [14:0] SFX_END   [1:8] = '{")
        f.write(", ".join(f"15'd{sfx_end[i]}" for i in range(1, 9)))
        f.write("};\n")

    print(f"Wrote {HW_DIR/'bgm_rom.mem'}, {HW_DIR/'sfx_rom.mem'}, {HW_DIR/'sfx_offsets.svh'}")


if __name__ == "__main__":
    main()
